### PR TITLE
Added new README.

### PR DESCRIPTION
**Pull request by ericlingerfelt**
## Description

This pull request adds a new README.MD file.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
I checked the preview in markdownlivepreview, and it looks good. Thanks!

**Comment by climbfuji** [comment]
@tariqhamzeyssai @BenjaminRuston We need one more review for this incredibly complex PR ...

**Review by tariqhamzeyssai — APPROVED** [review]

**Comment by ericlingerfelt** [comment]
@tariqhamzeyssai is not an approved reviewer. Please add him when you get the chance.

**Review by BenjaminRuston — COMMENTED** [review]
documenting the current state of affairs is good, improving is the next step

**Pull request merged**
