### PR TITLE
Fixing the storing part for tlapse

### PR DESCRIPTION
**Pull request by fabiolrdiniz**
## Description
This PR is fixing the storing part for the `obsbias_tlapse` files.

## Issue(s) addressed
Resolves https://github.com/JCSDA-internal/r2d2-ingest/issues/61

## Dependencies
None.

## Impact
None.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by huishao-r — APPROVED** [review]
Works! Thanks so much!

**Review by ericlingerfelt — APPROVED** [review]
Thanks, @fabiolrdiniz!

**Comment by ericlingerfelt** [comment]
@fabiolrdiniz, Is this ready to merge?

**Comment by fabiolrdiniz** [comment]
@ericlingerfelt, I missed your message above. Yes, it was. @huishao-r tested it in the ROMEX environment.

**Pull request merged**
